### PR TITLE
Implementation of ShowattendancePage at User End

### PR DESCRIPTION
**Pull request by spmshakti**
@RitwikSingh28 @rani620 
###  **Title**: Add ShowAttendance Page 

**Description:**
Implementation of ShowAttendance  Page and some widgets
Changes Made:

- user ->pages->showattendance_student.dart,
- user->widgets->showattendancewidgets->bottom_navbar.dart
- user->widgets->showattendancewidgets->
                                                                       1. attendance_calender.dart
                                                                       2. buildButton_user.dart
                                                                       3. debarredstatus.dart
                                                                       4. monthselector.dart
### 
### _**ScreenShot**_
photo_1

### CODE REVIEW

**Comment by dev04sa** [comment]
@spmshakti Some issue is there in your code regarding overflow.
try to fix this and also adjust the text BTech. on the top left corner.
WhatsApp Image 2024-03-30 at 12 15 58_b0870faf

**Review by piyuuussh — CHANGES_REQUESTED** [review]
Resolve the overflow issue...

**Comment by dev04sa** [comment]
@spmshakti try to solve merge conflicts correctly. You were  removed the image _picker dependency so that's why your code is giving error try to solve this one.

**Review by dev04sa — APPROVED** [review]
@spmshakti your code is working fine.

**Review by piyuuussh — APPROVED** [review]
Looks good merging into main

**Pull request merged**
