### PR TITLE
Firebase functionality implemented

### PR DESCRIPTION
**Pull request by piyuuussh**
The PR contain some minor changes in the UI according to the DB table also firebase is storing the user data and user image in the firebase. 
@Yashrajdps13 @dev04sa @RitwikSingh28

### CODE REVIEW

**Comment by RitwikSingh28** [comment]
@Yashrajdps13 @piyuuussh 
Since this has already been approved by @Yashrajdps13, shall I go ahead and merge this?

**Comment by RitwikSingh28** [comment]
Review the changes @dev04sa @Yashrajdps13

**Comment by Yashrajdps13** [comment]
> Review the changes @dev04sa @Yashrajdps13 

Looks good!

**Review by dev04sa — APPROVED** [review]
@piyuuussh , Good work!!.

**Pull request merged**
